### ISSUE TITLE
Wrong way to draw a line segment

### ISSUE THREAD

**Issue by DimaOshchepkov** [David-Pena/Cohen-Sutherland-Algorithm#1]
Thank you very much for this implementation. If I understand correctly, then to draw a segment you need to use 
```ax.plot([x1,x2], [y1,y2], color="darkred"`)``` instead of ```ax.plot([x1,y1], [x2,y2], color="darkred")```.

**Comment by David-Pena** [comment]
Hi @DimaOshchepkov,

I think you might be confused. The `ax.plot` function receives as a parameter `x, y array-like or scalar` because they are coordinates points (always made by an X and a Y value).

I tried running the algorithm with your suggestion and it doesn't seem to work correctly
![image](https://github.com/David-Pena/Cohen-Sutherland-Algorithm/assets/57303087/5bbe6c6e-db0c-4277-a73c-bf0cbae69039)
![image](https://github.com/David-Pena/Cohen-Sutherland-Algorithm/assets/57303087/2bfb48ac-3d81-44b9-aac2-ce3f799f3012)

But with the current `ax.plot([x1,y1], [x2,y2], color="darkred")` it seems to work as expected
![image](https://github.com/David-Pena/Cohen-Sutherland-Algorithm/assets/57303087/6f9757e9-a006-4454-bd9b-fa0bb5fc3d13)
![image](https://github.com/David-Pena/Cohen-Sutherland-Algorithm/assets/57303087/2fd43c37-b86d-42d8-ae91-6e1271ff28a3)

Could you elaborate more on your suggestion? Maybe there are some cases I'm not aware of 👨‍💻

**Comment by DimaOshchepkov** [comment]
In order for the window size to be displayed correctly, you also need to change the line 
```ax.add_patch(Rectangle((4,4), 10, 8, color="lightblue"))```
 to ``` ax.add_patch(Rectangle(( xMin, yMin), xMax - xMin, yMax - yMin, color="lightblue"))```, 
because 10 and 8 are the length and width from the specified point (4, 4).

Let's look at the second test. Line 
```clipLine(7, 9, 11, 4)```
 should process and draw a line from (7, 9) to (11,4). But with the original method of drawing a straight line, we see a segment from (7.8, 10) to (8, 5.25), but there should be a segment from (7.8, 8) (10, 5.25). By changing the display method to mine, everything is displayed as it should.
![Figure_1](https://github.com/David-Pena/Cohen-Sutherland-Algorithm/assets/92399769/84964766-9647-4c1b-a80a-fac6d3f012d3)

**Comment by David-Pena** [comment]
Including those changes indeed make the second case work. But I still see the issue for the first and last case. In the first one with your methods
![image](https://github.com/David-Pena/Cohen-Sutherland-Algorithm/assets/57303087/5b99ae22-84ce-45f6-93b1-2d3aae109f81)
In here there should be a segment drawn

Also the last case where the line is rejected
![image](https://github.com/David-Pena/Cohen-Sutherland-Algorithm/assets/57303087/aa1ff2e9-ed5f-4af6-a2a5-87a39e6f29d3)
You can not see the line

**Comment by DimaOshchepkov** [comment]
In the first case, the line degenerates into a point. In the second case, the line is completely discarded and is not displayed in the rectangular area.
